### ISSUE TITLE
Consider using docusaurus

### ISSUE THREAD

**Issue by cemremengu** [fastify/website-metalsmith#100]
https://docusaurus.io/en/
https://github.com/facebook/docusaurus

It has built-in i18n, search integration, theming, versioning, blog etc. geared towards opensource projects (used by some well known ones as well). It might be worth giving a try.

**Comment by delvedor** [comment]
I’m very happy with the current solution, it has served us very well in the past moths and I don’t think there is a good reason to change it :)

**Comment by cemremengu** [comment]
I am not saying the current solution is bad, don't get me wrong 😄 Just suggesting that there is something like this out there if someone is up for experimentation :)

**Comment by delvedor** [comment]
We already had this discussion in https://github.com/fastify/fastify/issues/722, and we agree to keep using the current system. If you want to try to see if you can improve the current solution, please go ahead! But it should be a significant improvement :P

**Comment by cemremengu** [comment]
Sorry, I didn't see that discussion. Closing this for now then. It is also a bold project for me to handle by myself in the foreseeable future 😄
