### ISSUE TITLE
Mia-Platform logo disappears

### ISSUE THREAD

**Issue by allevo** [fastify/website-metalsmith#103]
I don't know why but not all organizations listed [here](https://github.com/fastify/website/blob/master/src/website/data/organisations.yml) are not showed in the website.

**Comment by lmammino** [comment]
i can see the logos

<img width="1918" alt="screen shot 2019-01-19 at 10 06 12 am" src="https://user-images.githubusercontent.com/205629/51429194-e5db9a80-1bd1-11e9-904e-554e937f33bc.png">


Which os/browser are you using? Maybe an SVG compatibility issue...

**Comment by allevo** [comment]
me too... Nice.
I'll close this.
