### ISSUE TITLE
Dead link on lmammino.github.io/fastify page

### ISSUE THREAD

**Issue by dbauszus-glx** [fastify/website-metalsmith#122]
I really like the documentation you put on github pages. While trying to find out which template you use I noticed that the link to the layout home.html is actually dead.

Unfortunately; It's the one in the footer which asks for PR to improve the page itself.

![image](https://user-images.githubusercontent.com/22201617/54432712-dd12cb00-4721-11e9-9858-ca8955a284d3.png)

The link in question is: https://github.com/fastify/fastify/docs/_layouts/home.html

**Comment by lmammino** [comment]
Sorry, I just realized I expressed my question badly. I meant in which URL of the documentation you see the broken URL in the footer?

**Comment by dbauszus-glx** [comment]
It is on the page referenced in the title. https://lmammino.github.io/fastify/ 

I am not sure whether this is a dev build as the problem does not happen on the regular fastify page. I can't remember how I landed on your fork. I think I followed a link from one of your blogs to lmammino.github.io/fastify

**Comment by lmammino** [comment]
This was an old test for the website. Deleted it now. Closing this

Thanks again @dbauszus-glx for reporting this
