### ISSUE TITLE
Broken parser in "JSON Schema and Shared Schema support" table

### ISSUE THREAD

**Issue by ACXgit** [fastify/website-metalsmith#124]
In the [JSON Schema and Shared Schema support](https://www.fastify.io/docs/latest/Validation-and-Serialization/#json-schema-and-shared-schema-support) table there are two kinds of check marks, the thick and green one (I suppose the correct one) and the thin and black one, which should probably be rendered as a "X" or simply nothing. Probably a parser issue.

**Comment by delvedor** [comment]
The symbols are different also in the markdown in https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md#json-schema-and-shared-schema-support.

cc @Eomm

**Comment by Eomm** [comment]
> which should probably be rendered as a "X" or simply nothing

Nope, they should be all green ✔️

My Fira Code font fails 😂

![image](https://user-images.githubusercontent.com/11404065/55827981-b753c880-5b0b-11e9-9ff3-b85ce1b9c108.png)

**Comment by Eomm** [comment]
@lmammino I have merged the fix/typo. 
There is something I have to do in order to upload in the site?

Thank you

**Comment by Eomm** [comment]
@delvedor could you give me some tips about that? (the site is still with the bad icon)

**Comment by lmammino** [comment]
I'll trigger a new build from circle

**Comment by Eomm** [comment]
Icon ✔

![image](https://user-images.githubusercontent.com/11404065/56440692-75d0d380-62ea-11e9-9fd3-26eb472047c9.png)

You can close it ✌

**Comment by delvedor** [comment]
Thanks!

**Comment by ACXgit** [comment]
Thank you!
