### ISSUE TITLE
Typo: Middlewares

### ISSUE THREAD

**Issue by hn4a0d** [fastify/website-metalsmith#130]
There is no plural of 'middleware', just as with the noun 'software', it is countless.

References:
[https://en.wiktionary.org/wiki/software](https://en.wiktionary.org/wiki/software)
[https://www.wordhippo.com/what-is/the-plural-of/middleware.html](https://www.wordhippo.com/what-is/the-plural-of/middleware.html)
[https://english.stackexchange.com/questions/257120/middleware-vs-middlewares](https://english.stackexchange.com/questions/257120/middleware-vs-middlewares)

and, why not: [https://twitter.com/taylorotwell/status/530445528568709122](https://twitter.com/taylorotwell/status/530445528568709122)

**Comment by mcollina** [comment]
Awesome! Would you like to send a PR?

**Comment by SerayaEryn** [comment]
This was fixed in fastify/fastify#1850.
