### ISSUE TITLE
Deprecated  beforeHandler  in home page second example

### ISSUE THREAD

**Issue by lcsd** [fastify/website-metalsmith#139]
Deprecated  **beforeHandler**  in home page second example. Must use **preHandler**.

## Your Environment

- *node version*: none
- *fastify version*: >=2.10.0
- *os*: Linux Mint
- *any other relevant information*

**Comment by lmammino** [comment]
Thanks a lot @lcsd! Can you submit a PR? :)

**Comment by anthonyringoet** [comment]
This has been resolved.

![image](https://user-images.githubusercontent.com/576905/80949144-bb781580-8df3-11ea-859d-df394578d07b.png)
