### ISSUE TITLE
Docs site truncates text visually

### ISSUE THREAD

**Issue by mrchief** [fastify/website-metalsmith#141]
## 🐛 Bug Report

The docs site doesn't handle breakpoints correctly. As a result, overflowing text is unreadable 

![image](https://user-images.githubusercontent.com/781818/70650638-79202300-1c1d-11ea-9774-0e0413de5b42.png)

This issue happens on full screen on a 15in Macbook Pro as well as on smaller windows. To make things worse, horizontal scroll is disabled, so there is really no way to read the content (unless you zoom out and squint 😄) 

## To Reproduce

Open up docs site on a laptop. I tried on a Macbook Pro 15in on Chrome Version 78.0.3904.108 (Official Build) (64-bit)

## Expected behavior

Ideally, the docs site should be responsive to smaller screens and breakpoints. At the very least, it shouldn't disable horizontal scroll. 

## Your Environment

Macbook Pro 15in on Chrome Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by mcollina** [comment]
Would you like to send a PR?
Il 12 dic 2019, 07:58 -0500, Hrusikesh Panda <notifications@github.com>, ha scritto:

**Comment by mrchief** [comment]
@jsumners on full screen

![image](https://user-images.githubusercontent.com/781818/70767871-dc4eaa00-1d30-11ea-8324-6d4c1be04e14.png)

But it happens on smaller viewports as well (that are not so small)

![image](https://user-images.githubusercontent.com/781818/70767901-fa1c0f00-1d30-11ea-8026-f3b66d2705cd.png)

**Comment by lmammino** [comment]
I can look into this probably next week. If you have a solution in mind it will speed up things a lot to have a PR :)

Thanks a lot for reporting this! the website deserves much more love than it gets right now, so any chance to improve it is very welcome!
