### ISSUE TITLE
Contributors section: design improvement

### ISSUE THREAD

**Issue by lmammino** [fastify/website-metalsmith#146]
## 🚀 Feature Proposal

Hello, I was playing a bit with SVG clip paths and I got some interesting results that can be used to make the  contributors section in the home page a little bit more lively.

This is just an experiment, so be brutal on your feedback. If you like it tough, I will submit a PR :)

## Example

![Screen Shot 2020-01-14 at 10 24 24 AM](https://user-images.githubusercontent.com/205629/72336330-713e1d80-36b8-11ea-996b-0f2da704f0fd.png)

**Comment by mcollina** [comment]
i like it!

**Comment by jsumners** [comment]
👍

**Comment by Eomm** [comment]
Why not hexagon?
Like the stikers 😂

**Comment by lmammino** [comment]
@Eomm Here's a preview

<img width="986" alt="Screenshot 2020-01-14 at 21 18 02" src="https://user-images.githubusercontent.com/205629/72383463-6a90c400-3713-11ea-934e-e999cc0e90e0.png">

What do you guys think? 

I still prefer the diagonal stripes version 😛

**Comment by Eomm** [comment]
I like both versions 👍🏼 

I thought it could be a nice shape 😄

**Comment by delvedor** [comment]
I like both! But the hexagon might be more related to the Node.js style :D
