### ISSUE TITLE
The "docs" link from the top bar should point to the docs for the last release instead of master

### ISSUE THREAD

**Issue by mcollina** [fastify/website-metalsmith#154]
## 🐛 Bug Report

The top link points to the docs on `master` rather than the docs on the released version.
It should point to the latest release instead.

**Comment by jsumners** [comment]
![image](https://user-images.githubusercontent.com/321201/73594736-16415e80-44df-11ea-9711-6472bc484de1.png)

**Comment by lmammino** [comment]
Closed by #160 🎉
