### ISSUE TITLE
latest docs should point to the latest non-experimental release, not master

### ISSUE THREAD

**Issue by mcollina** [fastify/website-metalsmith#157]
Currently in the https://www.fastify.io/ top banner, we point to docs of master.
With the upcoming v3 release, this would soon be experimental/alpha. So, we should point the docs to the latest stable version.

**Comment by mcollina** [comment]
cc @lmammino

**Comment by lmammino** [comment]
Let me review the current logic. As far as I remember it is based on branches and tags, so it might just work as it is. I'll reply back here as soon as I have more clarity or some questions.

(Apologies for the delay, very busy days lately)

**Comment by lmammino** [comment]
Ok, I think I have now clear the current approach:

- We download all the releases after a given release (using [the GitHub releases endpoint](https://api.github.com/repos/fastify/fastify/releases)). Currently, we download all from most recent until `1.13.x`.
- We also download the current `master` and we mark it a `master`.
- The `latest` release is determined as the "highest" release after `master` as dictated by a [dedicated sorting function](https://github.com/fastify/website/blob/master/src/scripts/utils/sortVersionTags.js).

If we do a GitHub release called `3.x.y` that will become the `latest`. Is this something we don't want? Can you describe a bit more how do you plan to organise the release of v3 over time? Once we have that defined I should be able to simulate releases, test and adjust the code if needed.

**Comment by mcollina** [comment]
It's not working like that: latest is master right now.

We will release v3.0.0-alpha.0 and so on.

**Comment by lmammino** [comment]
Will `master` be `v3.0.0-alpha.0` as soon as `v3.0.0-alpha.0` is released?

Or do you plan to keep `3.x` in its own branch?

**Comment by mcollina** [comment]
I think so, yes.

However master should never be "latest"
Il 10 mar 2020, 23:22 +0100, Luciano Mammino <notifications@github.com>, ha scritto:

**Comment by lmammino** [comment]
ok, thanks!

Just to clarify: latest will be **latest stable** (2.x) or any latest (highest) version (3.x)?

In other words, do we need to start tracking what's stable and what's beta and treat them differently?

**Comment by mcollina** [comment]
Any latest version that does not have a `-something.somethingelse` at the end.

**Comment by lmammino** [comment]
Sounds good. I'll try to find some time to make the necessary changes. When do you expect to ship 3.0.x?

**Comment by mcollina** [comment]
I think we'll ship ready to ship an alpha in the next few weeks.

**Comment by lmammino** [comment]
Started working on this. Also found a bug whereby we might have missed releases as we look only at the first page of the releases API call 😓

Doing some testing and refactoring, it might take me a bit but I hope I will have the PR open by the end of the week
