### ISSUE TITLE
Keep update ecosystem page

### ISSUE THREAD

**Issue by allevo** [fastify/website-metalsmith#16]
How can we keep update the ecosystem list?

**Comment by lmammino** [comment]
At the moment It is managed by a [static yaml file](https://github.com/fastify/website/blob/master/src/website/data/ecosystem.yml).

It could be a nice idea to automate the generation of this file by extrapolating the list from the README in master at build time, similar to how we do that currently to handle documentation.

**Comment by lmammino** [comment]
@allevo just submitted a PR that should fix this. Please have a look and let me know what you think

**Comment by lmammino** [comment]
Any reason why this issue was closed? The PR, once (and if) merged, should have closed it IMHO.

**Comment by allevo** [comment]
The issue was opened in order to open a PR.
Once a PR is made, this is not needed.

We can move the discussion to PR for thoughts sharing.
