### ISSUE TITLE
Website shows current `master` docs instead of latest release

### ISSUE THREAD

**Issue by jsumners** [fastify/website-metalsmith#166]
This is becoming a much bigger issue now that we are in the v3 pre-release phase. People are reading the docs on the website and trying to apply them to their v2 install. As a result, they are creating "readme code doesn't work" issues. The website should default to current non-prerelease.

FWIW, this script will show the latest release's details:

```sh
#!/bin/bash
curl -s https://api.github.com/repos/fastify/fastify/releases | \
  jq -r 'map(select(.draft == false and .prerelease == false)) | map(select(.name | test("v.+"))) | .[0]'
```

**Comment by mcollina** [comment]
cc @lmammino can you take a look?

also @GlenTiki might be a good one if you'd like to take a stab at it!

**Comment by GlenTiki** [comment]
I'll happily take a look this evening if no fix has been posted yet. 👍

**Comment by lmammino** [comment]
Hey, guys sorry for the delay.
I have been super busy in the latest weeks.

I am not sure I understand the issue. Right now, we are pointing the documentation to `latest` by default.

`latest` (https://www.fastify.io/docs/latest/) already skips `draft` and `prerelese` releases and selects the most recent one. At this very moment, `latest` is `v2.13.1`.

`master` (https://www.fastify.io/docs/master/) just takes whatever is in the `master` branch at build time and builds the documentation out of it. With the current setup, a user has to manually and intentionally switch to `master` to see `master` documentation though, so I am not sure where the source of confusion is coming from.

Could you please elaborate a bit more on what we should change to make things more clear for the users?

**Comment by jsumners** [comment]
It must have been because `pre-release` wasn't ticked off on the `v3.0.0-alpha.1` release.

**Comment by lmammino** [comment]
Good to know this doesn't require any fundamental change on the build flow. 😬

Thanks for clarifying @jsumners
