### ISSUE TITLE
latest doc alias

### ISSUE THREAD

**Issue by mcollina** [fastify/website-metalsmith#17]
as title, we should be able to do:

http://www.fastify.io/docs/latest/Getting-Started/

(this should point to the latest released version of the guide)

**Comment by lmammino** [comment]
Good point!

So far we can do something similar only for `master`. It shouldn't be hard to update the code based on that example.

I will try to address this at some point this week.

**Comment by lmammino** [comment]
Just as reminder to myself:
---

For avoiding SEO issues with duplicated content, all the pages in `latest` should have a meta:

```html
<link ref="canonical" href="/docs/<latest_release_version>/">
```
