### ISSUE TITLE
Wrong docs on v2

### ISSUE THREAD

**Issue by Eomm** [fastify/website-metalsmith#174]
#  🐛 Bug Report

The docs in the site are different from the repo.

## To Reproduce

v2 repo shows the right interface:
https://github.com/fastify/fastify/blob/2.x/docs/Hooks.md#preparsing

```
fastify.addHook('preParsing', (request, reply, done) => {
```

The site shows the v3 interface:
https://www.fastify.io/docs/v2.15.x/Hooks/#preparsing

![image](https://user-images.githubusercontent.com/11404065/86257563-01feac00-bbba-11ea-957e-bd0e4b01f650.png)

**Comment by mcollina** [comment]
@lmammino can you take a look?

**Comment by mcollina** [comment]
Fixed, it was the wrong tag.

**Comment by lmammino** [comment]
Apologies I did miss the previous notifications and seeing this only now :/
