### ISSUE TITLE
Redirect to Server.inject for testing purposes gives 404 

### ISSUE THREAD

**Issue by ghost** [fastify/website-metalsmith#177]
## 🐛 Bug Report

I was reading the documentation related to [Server.inject](https://www.fastify.io/docs/latest/Server/#inject).
It says that I can read more about `fake http injection (for testing purposes)` following [this](https://www.fastify.io/docs/latest/Server/Testing.md#inject) link. However, I've got a `404` error.

## To Reproduce

- Go to the documentation on `Server.inject`: https://www.fastify.io/docs/latest/Server/#inject
- Then click on the `here` hyperlink, it should redirect you to https://www.fastify.io/docs/latest/Server/Testing.md#inject
- Receive `404 Content not found`

## Expected behavior

I should be redirected to the correct page where I can read the information and see code examples. 

I believe I should be redirected to https://www.fastify.io/docs/latest/Testing/#benefits-of-using-fastifyinject

## Your Environment

- *os*: Mac
- *browser*: Brave (Chromium)

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue?
