### ISSUE TITLE
Redirect to Routes section gives 404

### ISSUE THREAD

**Issue by ghost** [fastify/website-metalsmith#178]
## 🐛 Bug Report

I was reading the documentation related to [Server.route](https://www.fastify.io/docs/latest/Server/#route).
It says that I can read `method to add routes to the server, it also has shorthand functions, check ...` [here](https://www.fastify.io/docs/latest/Server/Routes.md). However, I've got a `404` error.

## To Reproduce

- Go to the documentation on `Server.route`: https://www.fastify.io/docs/latest/Server/#route
- Then click on the `here` hyperlink, it should redirect you to https://www.fastify.io/docs/latest/Server/Routes.md
- Receive `404 Content not found`

## Expected behavior

I should be redirected to the correct page where I can read the information and see code examples. 

I believe the redirection should go to https://www.fastify.io/docs/latest/Routes/

## Your Environment

- *os*: Mac
- *browser*: Brave (Chromium)

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
