### ISSUE TITLE
Redirect to Server.decorate* gives 404

### ISSUE THREAD

**Issue by ghost** [fastify/website-metalsmith#179]
## 🐛 Bug Report

I was reading the documentation related to [Server.decorate](https://www.fastify.io/docs/latest/Server/#decorate).
It says that `Function useful if you need to decorate the fastify instance, Reply or Request, check ...` [here](https://www.fastify.io/docs/latest/Server/Decorators.md). However, I've got a `404` error.

## To Reproduce

- Go to the documentation on `Server.decorate`: https://www.fastify.io/docs/latest/Server/#decorate
- Then click on the `here` hyperlink, it should redirect you to https://www.fastify.io/docs/latest/Server/Decorators.md
- Receive `404 Content not found`

## Expected behavior

I should be redirected to the correct page where I can read the information and see code examples. 

I believe I should be redirected to https://www.fastify.io/docs/latest/Decorators/

## Your Environment

- *os*: Mac
- *browser*: Brave (Chromium)

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue?

**Comment by ghost** [comment]
@mcollina 

Definitely. I've found a lot of such things throughout the docs. It's a bit annoying. I'll take all the `issues` opened by me and address those problems.

**Comment by mcollina** [comment]
Thanks!

**Comment by ghost** [comment]
That's broken only for the following versions:
* `v3.0.x`
* `master`
* `latest`

I guess I've found the issue. I'm looking for a solution :)

**Comment by ghost** [comment]
@mcollina the fix may require the change to the `fastify` repo. Is it okay?

**Comment by mcollina** [comment]
yes! Go for it
