### ISSUE TITLE
Validation and Serialization page 404

### ISSUE THREAD

**Issue by tnguyen14** [fastify/website-metalsmith#181]
The Errors page has a link to "JSON.schema validation", which is https://www.fastify.io/docs/latest/Errors/Validation-and-Serialization.md

That page is returning a 404.

**Comment by lmammino** [comment]
Thanks for this bug report @tnguyen14.

This seems to happen with other links in the docs: specifically all the ones in the format `[some labed](./some-page.md)`. The `./` works correctly on github but it's not remapped correctly in our docs.

This could be done [here](https://github.com/fastify/website/blob/master/src/scripts/processReleases.js#L144). Apparently we should already handle that but probably there is some case that is not currently covered by the regex (probably when there is an anchor at the end of the link).

I won't have a lot of time in the next few weeks to have a look at this, I would love it if you could contribute with a PR to fix this.

**Comment by Eomm** [comment]
These errors are related to https://github.com/fastify/fastify/issues/2421#issuecomment-660635888
