### ISSUE TITLE
Rebuild a website and deploy a new version

### ISSUE THREAD

**Issue by ghost** [fastify/website-metalsmith#182]
## 🐛 Bug Report

404 Errors on the website should have been fixed by https://github.com/fastify/fastify/pull/2434 yet those errors still present on the website. Thus, it would be nice to rebuild the website and deploy a new version, which will fix those things.

## To Reproduce

* Go to the documentation on Server.decorate: https://www.fastify.io/docs/latest/Server/#decorate
* Then click on the here hyperlink, it should redirect you to https://www.fastify.io/docs/latest/Server/Decorators.md
* Receive 404 Content not found
and many others

## Expected behavior

A user should be redirected to the correct page where they can read the information and see code examples.

## Your Environment

- *os*: Mac

**Comment by lmammino** [comment]
Just retriggered [a build](https://app.circleci.com/pipelines/github/fastify/website/213/workflows/7edda522-23ec-4c48-8838-2776b38ec9d5/jobs/2303). Hopefully this will fix the issue.

Thanks for opening this issue @iandrc !

**Comment by lmammino** [comment]
Unfortunately retriggering the build didn't help. I still see `./something` type of links in the build.

<img width="503" alt="Screenshot 2020-07-28 at 13 14 38" src="https://user-images.githubusercontent.com/205629/88664028-5a02d280-d0d4-11ea-8aaf-d04ddcf9e4e8.png">


I'll try to run a local build at some point later today.

**Comment by ghost** [comment]
@lmammino Maybe we'll need to wait for another `fastify` version release

**Comment by lmammino** [comment]
Just managed to spend some time on this (finally) and it seems that in `master` the latest changes are reflected, but they still don't help to solve the issue. In fact `./page.md` and `page.md` are resolved exactly in the same way by the browser (still relative link from the current URL).

This requires code changes in the build process to remap these links correctly. I will submit a PR shortly

**Comment by lmammino** [comment]
@iandrc can you help me validating that the changes proposed in https://github.com/fastify/website/pull/183 are solving the issue as expected?

Thanks :)
