### ISSUE TITLE
Broken link on ContentTypeParser page

### ISSUE THREAD

**Issue by mbarzeev** [fastify/website-metalsmith#188]
## 🐛 Bug Report

There is a broken link on the [ContentTypeParser](https://www.fastify.io/docs/latest/ContentTypeParser/) page, in the `See example/parser.js for an example.` caption.

## To Reproduce

Go to the page, look for `See example/parser.js for an example.` and click the link

## Expected behavior
The JS example file should be displayed

I wanted to edit the doc myself but it seems to be generated, and the branch from which the docs were generated has meaning, so I didn't know exactly how to resolve that.

**Comment by mcollina** [comment]
cc @lmammino

**Comment by lmammino** [comment]
Great catch @mbarzeev. This is a case that is currently not covered by our url remapping logic in the website build pipeline. I think we should link this one straight to the github page for the js file.

I'll try to find some time to fix this during the weekend

**Comment by mbarzeev** [comment]
Hi @lmammino,
By "link this one straight to the github page for the js file", to which branch are you aiming for, Master?
If you are aiming for a static link I can create a PR for this, and save you some time ;)

**Comment by Eomm** [comment]
I think he is referring to this:

https://github.com/fastify/website/blob/616eb8c988d2c8a905c938839c91a725e9b87bbc/src/scripts/processReleases.js#L144

the site downloads the docs from `fastify` repo and then fixes the links thought that function that is processing this URL as well:

```
See [`example/parser.js`](../examples/parser.js) for an example.
```

Right now we should have fixed all the links to relative ones, so maybe could we leave absolute link untouched?

**Comment by luisorbaiceta** [comment]
Current remapping logic covers this case
