### ISSUE TITLE
Broken link on the Getting Started doc page

### ISSUE THREAD

**Issue by eadsjr** [fastify/website-metalsmith#189]
## 🐛 Bug Report

The relative link to Ecosystem on the getting started doc under the 'Extend your server' header works fine on github, but dies on the website.

## To Reproduce

At location https://www.fastify.io/docs/latest/Getting-Started/#extend-your-server

Click the link for ecosystem.

 It goes to https://www.fastify.io/docs/latest/Ecosystem which 404s.

## Expected behavior

It should have gone to https://www.fastify.io/ecosystem

## Your Environment

OS X 10.15.3
Chrome Version 84.0.4147.125 (Official Build) (64-bit)

**Comment by anthonyringoet** [comment]
Seems to be fixed
