### ISSUE TITLE
Typo on ecosystem page regarding fastify-websocket

### ISSUE THREAD

**Issue by devlzcode** [fastify/website-metalsmith#212]
Tiny typo, mentions that fastify-websocket is built upon _websocket-stream_ instead of **ws** (the official repo says ws)

**Comment by lmammino** [comment]
Hello @lenneths! thanks for reporting this. The data on the website is taken at build time from one of the READMEs on the main project (https://github.com/fastify/fastify/blob/master/docs/Ecosystem.md#community). Would you like to contribute to the project by opening a PR there?

**Comment by anthonyringoet** [comment]
Recently fixed: https://github.com/fastify/fastify/pull/3311
