### ISSUE TITLE
404 Fasitfy Website: TypeScript page, CONTRIBUTING.md anchor tag broken link

### ISSUE THREAD

**Issue by FernandoBoza** [fastify/website-metalsmith#229]
## 🐛 Bug Report

https://github.com/fastify/website/blob/master/src/website/content/404.md

## To Reproduce

Go to https://www.fastify.io/
Navigate to https://www.fastify.io/docs/latest/
Navigate to https://www.fastify.io/docs/latest/TypeScript/
Navigate to https://www.fastify.io/docs/latest/CONTRIBUTING.md

## Expected behavior

🤔 https://github.com/fastify/fastify/blob/master/CONTRIBUTING.md 🤔 

## Your Environment

- *node version*: v14.7.0
- *fastify version*: >= 3.11.0
- *os*: Mac

**Comment by lmammino** [comment]
Thanks a lot @FernandoBoza for reporting this.

I realized that also the links at the bottom (`src` links) are affected by the same problem.

There are 2 solutions for this problem:

  1. use absolute links in the source file for this page (https://github.com/fastify/fastify/blob/master/docs/TypeScript.md)
  2. update the link remapping rules from the source on github to the website (https://github.com/fastify/website/blob/master/src/scripts/processReleases.js#L144-L170)
  
 Would you like to contribute and help us to address this problem?

**Comment by FernandoBoza** [comment]
@lmammino i'd be happy to help, 

i believe  switching out the links the current source file for this https://github.com/fastify/fastify/blob/master/docs/TypeScript.md would be the fastest option. FYI just brand new to open source
