### ISSUE TITLE
Decorate hyperlink <a> tags to make them stand out

### ISSUE THREAD

**Issue by Fdawgs** [fastify/website-metalsmith#237]
## 🚀 Feature Proposal

Change links to a different color, or decorate them i.e. bold or underline.

## Motivation

This may be the result of my color blindness, but the links and text use colors that are too similar, meaning that links just blend in with the text.
This makes it easy for links to be missed when reading a page.

As an example, in the image below I can't tell from a glance that `more organisations using Fastify` is a link 😢 

![Capture](https://user-images.githubusercontent.com/43814140/108106526-f6e38800-7085-11eb-85cf-06adafa1e5fb.PNG)

**Comment by lmammino** [comment]
Great suggestion @Fdawgs! I honestly went with the defaults provided by Bulma, but I totally see your point. 

It shouldn't be particularly complicated to change this by updating our sass files. Is this something you'd be willing to look at?

**Comment by Fdawgs** [comment]
I'll have a go! Not too sure on what the best approach would be though?

Color change? Underline? Is there a preference?

**Comment by lmammino** [comment]
I'd personally prefer a colour change, but I am not strongly opinionated about it, nor I am particularly skilled with accessibility. So I suppose whatever is the most accessible option, we should probably pursue it...
