### ISSUE TITLE
[Discussion] Possibility to automatically generate benchmarks file

### ISSUE THREAD

**Issue by lmammino** [fastify/website-metalsmith#24]
It would be nice if we can somehow automatically generate [the file used as data source](https://github.com/fastify/website/blob/master/src/website/data/benchmarks.yml) to render the [benchmarks page](http://www.fastify.io/benchmarks/), so that we might be able to easily keep the page in sync with the evolution of the benchmarks.

I haven't dig in depth into this yet, so I can't propose a complete solution, but I'd love to raise the issue anyway, maybe you already have an easy solution in mind.

**Comment by salesh** [comment]
Hi @lmammino,

What you think about creating a script that would scrape from https://github.com/fastify/benchmarks?
Benchmarks GitHub has an action that every first day in a month regenerates data so we could have action here that will every second day in a month call our script, modify benchmarks.yml, and commit a modified version. What do you think about this?

**Comment by mcollina** [comment]
I think the best path forward is to have the benchmarks repo publish the data in json as well as in markdown, and fetch it while we render the website.

**Comment by salesh** [comment]
Hi Matteo @mcollina should I then first create PR with modification in benchmark-compare.js that will create benchmark-result.json?

**Comment by mcollina** [comment]
The data is already created in a folder, but not committed by the github action. We should just make the action commit it.

**Comment by salesh** [comment]
Sorry if I am wrong Matteo @mcollina but like you mention they are in the uncommitted folder results and then the benchmark-compare.js script goes through each of them and creates output (called in GActino)- wouldn't there be a place to just create benchmark-result.json (with merged desired output that we want to get with a request) when we are traversing result dir. after finishing the loop?

**Comment by mcollina** [comment]
That's also ok!

**Comment by luisorbaiceta** [comment]
Current website is automatically generating benchmarks on build process
