### ISSUE TITLE
Run local site on Windows

### ISSUE THREAD

**Issue by Eomm** [fastify/website-metalsmith#240]
On win bad thinks are happening.

There is a [workaround](https://github.com/fastify/website/pull/143#issuecomment-573112072):

In the `src\scripts\buildWebsite.js` file change the script:

https://github.com/fastify/website/blob/97ff86e9d1a1aa8d100a5f33e01cc5c8be59ed69/src/scripts/buildWebsite.js#L75-L77

To:

```
  .use(
    function (files, ms, done) {
      var metadata = ms.metadata()
      metadata.hashes = metadata.hashes || {}
      var relevantFiles = Object.keys(files)
      relevantFiles.forEach(function (filepath) {
        metadata.hashes[filepath.replace(/\\/ig, '/')] = filepath
      })
      return process.nextTick(done)
    }
  )
```

Or send a PR to [metalsmith-contenthash](https://github.com/ekytr/metalsmith-contenthash#readme)

> 
> The easiest way to test your changes is to do `npm run start:dev`. It should open a browser window for you. Every time you change a file it should rebuild and refresh automatically (with some lag 😅)
> 
> Let me know if this helps or if you get stuck with something

I do attempt to test the changes locally however the resources don't load 😞   :
![Capture](https://user-images.githubusercontent.com/43814140/108187881-da3b6480-7106-11eb-80e5-eea6a0041acf.PNG)

The following errors are thrown in the console:

`The stylesheet http://127.0.0.1:8080/ was not loaded because its MIME type, “text/html”, is not “text/css”.`
`The script from “http://127.0.0.1:8080/” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.`

Tested using both Edge 88.0.705.68 and Firefox 85.0.2

_Originally posted by @Fdawgs in https://github.com/fastify/website/issues/238#issuecomment-780442720_

**Comment by Fdawgs** [comment]
Can be closed as resolved by https://github.com/fastify/website/pull/263 😁
