### ISSUE TITLE
Running on Wsl 

### ISSUE THREAD

**Issue by veritem** [fastify/website-metalsmith#246]
## 🐛 Bug Report

Development server doesn't start on wsl

## To Reproduce

![image](https://user-images.githubusercontent.com/53856673/112754805-17d0be80-8fde-11eb-9e50-877b624b2b43.png)

After Running `npm install` and running `npm start:dev`

To start a dev server

## Expected behavior

Should start the development server

## Your Environment

- *node version*: v14.16.0
- *fastify version*: >=2.0.0
- *os*: Linux
- Wsl

**Comment by mcollina** [comment]
Would you help fixing this? I think it's due to most of us having Linux or Mac systems.

**Comment by simoneb** [comment]
Works for me on Win 10 on Node 12/14 on all of:

- cmd
- mingw
- wsl

The only clue is, if you're running `npm start:dev` it may mean you're running npm@7, so that may be part of the issue. Just guessing, haven't tried it. I recommend to stick to the npm version that ships with your Node version.

**Comment by jsumners** [comment]
> I recommend to stick to the npm version that ships with your Node version.

💯

If it isn't bundled with Node.js LTS, it isn't an `npm` I consider even exists.

**Comment by veritem** [comment]
Yeah,@simoneb  I run  `npm start:dev` still not working on win 10 wsl with ubuntu 20.04 using node `v14.16.0`

**Comment by simoneb** [comment]
If you're running npm@7, try switching back to npm@6

**Comment by veritem** [comment]
I'm on npm@7 I don't understand how npm version affects the build though

**Comment by jsumners** [comment]
`npm@7` installs modules with a different algorithm than `npm@6`. In particular, it reverts the behavior around `peerDependencies`. It also completely changes the lock file format.

**Comment by veritem** [comment]
We can try to update the repo to run even on npm@7?

**Comment by Fdawgs** [comment]
Potentially closed by https://github.com/fastify/website/pull/263?

**Comment by lmammino** [comment]
I think so, @Fdawgs. I'd say let's close this one for now. We can always reopen if the problem still persists under some particular configuration.

**Comment by luisorbaiceta** [comment]
This is now working with WSL(ubuntu 20.04) on node v14.16.0 and npm v7
