### ISSUE TITLE
Docs: Misaligned Diagrams on Lifecycle page

### ISSUE THREAD

**Issue by shuta13** [fastify/website-metalsmith#255]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.15.1

### Node.js version

12.4.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.15.7

### Description

Diagrams on Lifecycle page looks broken, as shown in the following images.

<img width="640" alt="lifecycle-diagram" src="https://user-images.githubusercontent.com/38882716/118946798-b69bea80-b991-11eb-935e-5c457712e31a.png">

<img width="640" alt="reply-lifecycle-diagram" src="https://user-images.githubusercontent.com/38882716/118946808-b8fe4480-b991-11eb-8979-69af38913908.png">

### Steps to Reproduce

Open Lifecycle page in Fastify Docs : <https://www.fastify.io/docs/latest/Lifecycle/>

### Expected Behavior

It would be nice if those would look like what are displayed on GitHub.

<img width="640" alt="lifecycle-diagram-github" src="https://user-images.githubusercontent.com/38882716/118949862-9ae61380-b994-11eb-9c95-c41bd6555e41.png">

<img width="640" alt="reply-lifecycle-diagram-github" src="https://user-images.githubusercontent.com/38882716/118949527-4c387980-b994-11eb-93b7-054f25b4c542.png">

I think it can be fixed by setting [CSS word-spacing](https://developer.mozilla.org/en-US/docs/Web/CSS/word-spacing) to an appropriate value. Another option would be to replace diagrams with images.

**Comment by lmammino** [comment]
Hey, Thanks a lot for reporting this!

We would really appreciate if you would have some time to help us address this by submitting a PR.

**Comment by shuta13** [comment]
@lmammino 
All right, I'll try to fix that!

**Comment by lmammino** [comment]
Thanks a lot. Note that I am not able to replicate the issue (on mac/google-chrome), so I am thinking it could be a font-related problem...

**Comment by shuta13** [comment]
> so I am thinking it could be a font-related problem...

I checked it out, and you're right. 

I set the  `font-family` of `code` to be the same as on GitHub, and that fixed this problem. I'll submit a PR.

<img width="640" alt="fixed-lifecycle-diagram" src="https://user-images.githubusercontent.com/38882716/118967402-a0982500-b9a5-11eb-96d1-13d47cc9c786.png">
