### ISSUE TITLE
Team section doesn't align with that in Fastify repo

### ISSUE THREAD

**Issue by Fdawgs** [fastify/website-metalsmith#266]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.18.0

### Plugin version

1.x.x

### Node.js version

14.x.x

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

List of team members in https://github.com/fastify/website/blob/master/src/website/data/team.yml doesn't align with the list of team members in https://github.com/fastify/fastify#team, primarily the "past collaborators".

Not too sure which is the most current/up-to-date?

### Steps to Reproduce

Contrast and compare lists

**Comment by mcollina** [comment]
The README in the project is the source of truth.
