### ISSUE TITLE
Prevent robot crawl on old version of document

### ISSUE THREAD

**Issue by climba03003** [fastify/website-metalsmith#271]
## 🚀 Feature Proposal

Add the meta when generating old version of document.
```html
<meta name="robots" content="noindex">
```

## Motivation

We can see that some search engine is crawling the old document and it will mislead some of the users.
e.g. https://github.com/fastify/fastify/issues/3255

**Comment by mcollina** [comment]
what do you mean by old document?

**Comment by climba03003** [comment]
> 
> 
> what do you mean by old document?

old version of document.
For example inside the issue I link, it always search for the version `1.XX.X`.

**Comment by climba03003** [comment]
Close by #276
