### ISSUE TITLE
SEO: disable indexation of previous versions

### ISSUE THREAD

**Issue by zekth** [fastify/website-metalsmith#272]
## 🚀 Feature Proposal

adding this meta tag on non latest documentation page of the library:
```html
<meta name="robots" content="noindex, nofollow">
```

## Motivation

We get some issues coming here and there from old versions of the library. Leading to potentially bad developer experience.

## Example

See: https://github.com/fastify/fastify/issues/3252

**Comment by climba03003** [comment]
I think we are talking about the same thing.
#271

**Comment by zekth** [comment]
Indeed duplicate. Sorry.
