### ISSUE TITLE
Good first issue plugin error

### ISSUE THREAD

**Issue by Eomm** [fastify/website-metalsmith#279]
On the page https://www.fastify.io/contribute/
I'm getting this error

![image](https://user-images.githubusercontent.com/11404065/131837426-72f05954-25fa-4d74-bb54-69737e48548c.png)

response error headers:

```
x-vercel-error: INTERNAL_DEPLOYMENT_FETCH_FAILED
x-vercel-id: fra1::cz46f-1630582905494-89410667278e
```

**Comment by lmammino** [comment]
@GlenTiki, is this an issue with the backend lambda? Shall we host it elsewhere?

**Comment by lmammino** [comment]
Btw, this seems to work right now

**Comment by GlenTiki** [comment]
This is hosted on now.sh IIRC, it could have just been a blip on their end. I'll look into migrating that soon, now is deprecated.

**Comment by mcollina** [comment]
We could deploy this with google cloud run, we have an account. I can set up a repo if you'd like.

**Comment by GlenTiki** [comment]
I don't mind! The code that powers this originally is here:
https://github.com/GlenTiki/gh-issue-finder

**Comment by simoneb** [comment]
It's looking good to me 

![image](https://user-images.githubusercontent.com/20181/132353540-a1507db8-8a9b-49c7-b530-c902261f908b.png)

**Comment by simoneb** [comment]
This is happening again. Considering that we don't need the UI and the only API endpoint is extremely simple, I suggest that we rewrite and self-host it.

**Comment by xkal36** [comment]
I will pick this up
