### ISSUE TITLE
Not seeing guides

### ISSUE THREAD

**Issue by jsumners** [fastify/website-metalsmith#280]
### Description

https://github.com/fastify/website/pull/269

I am not seeing the result of that work on https://www.fastify.io/docs/master/ . Should I be?

@lmammino

**Comment by jsumners** [comment]
Also isn't showing up in the latest versioned release -- https://www.fastify.io/docs/v3.21.x/

@luisorbaiceta

**Comment by luisorbaiceta** [comment]
Is it possible that changes haven't been deployed yet?

**Comment by jsumners** [comment]
I don't know how this works.

**Comment by luisorbaiceta** [comment]
I think that changes need to be merged to the `gh-pages` branch. But as I don't have permissions to check the automated build pipeline, I am not really sure. @lmammino

**Comment by jsumners** [comment]
https://app.circleci.com/pipelines/github/fastify/website/832/workflows/4cdd0634-d7ff-462b-b3fb-e648710b3c81/jobs/2687

**Comment by luisorbaiceta** [comment]
FOUND THE BUG. Would It be possible for you to rename the `Index.md` file inside the guides to `index.md`? 

https://github.com/fastify/website/blob/2931e2fdeebe92adfb350d64640a48e4ec00cd52/src/scripts/processReleases.js#L60

https://github.com/fastify/website/blob/2931e2fdeebe92adfb350d64640a48e4ec00cd52/src/website/layouts/docs_version_index.html#L48

https://github.com/fastify/website/blob/2931e2fdeebe92adfb350d64640a48e4ec00cd52/src/website/layouts/docs_page.html#L33

**Comment by jsumners** [comment]
Do a case insensitive match here.

**Comment by luisorbaiceta** [comment]
> Do a case insensitive match here.

It would really simplify a lot of renaming specially for the index page of the section. If we decide to do a case insensitive match as you are suggesting, then we will need to rename the `Index.md` file to `index.md` anyway if we want the route to be `...../docs/latest/Guides` instead of `...../docs/latest/Guides/Index`

**Comment by jsumners** [comment]
The website build should accept any case in my opinion.

**Comment by luisorbaiceta** [comment]
It does support any case except for the index files, which in my opinion makes sense because the default behaviour of the website is to render index.html files as root of the folder they are contained in

**Comment by jsumners** [comment]
The build should handle whatever case is found. I'm not [in condition](https://jrfom.com/posts/2021/09/03/a-bike-crash/) to debate much. Whatever can be done to fix the problem should be done.

**Comment by luisorbaiceta** [comment]
> The build should handle whatever case is found. I'm not [in condition](https://jrfom.com/posts/2021/09/03/a-bike-crash/) to debate much. Whatever can be done to fix the problem should be done.

Sorry to hear that! Get well soon!

I will see if I can find time next week to address this issue
