### ISSUE TITLE
Add support for Reference-style Links

### ISSUE THREAD

**Issue by luisorbaiceta** [fastify/website-metalsmith#298]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Improve [`remapLinks`](https://github.com/fastify/website/blob/944247a26dd331f34bb5dfaf240fdff34badc87f/src/scripts/processReleases.js#L176) method to support markdowns [Reference-style Links](https://www.markdownguide.org/basic-syntax/#reference-style-links) conversion.

The problem has anything to do with the renderer, after some research I found that `marked` fully supports this type of links.

### Motivation

A docs reorganization (fastify/fastify#3474) is taking place right now, and in order to support every possible scenario when linking for the new docs, this needs to be landed.

**Comment by jsumners** [comment]
@luisorbaiceta do you have time to point out the locations in the code that need to be changed?

**Comment by luisorbaiceta** [comment]
I have pointed it in the description. The method that needs to target those links with regex is `remapLinks`

**Comment by jsumners** [comment]
https://github.com/fastify/website/blob/944247a26dd331f34bb5dfaf240fdff34badc87f/src/scripts/processReleases.js#L176-L208

**Comment by luisorbaiceta** [comment]
closed this in #307
