### ISSUE TITLE
Broken rendering of Fastify main branch

### ISSUE THREAD

**Issue by mcollina** [fastify/website-metalsmith#305]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Description

The following link is a 404: https://www.fastify.io/docs/master/Reference/index.md.

See https://www.fastify.io/docs/master/ < the links generated are wrong there.

### Steps to Reproduce

See above

**Comment by mcollina** [comment]
cc @luisorbaiceta

**Comment by luisorbaiceta** [comment]
Yes, I was checking it right now. Rest is correctly linked for what I have checked. I will send a PR asap

**Comment by luisorbaiceta** [comment]
[problem](https://github.com/fastify/website/blob/f259836dd11c1b0d36e8e07a7f5c8ef8b29ec83a/src/scripts/processReleases.js#L249) is still here. If anyone in @fastify/core has experience with regex it would be much appreciated. We just need that line to match `[foo bar](./foo/bar.md)` or `[foo bar]: ./foo/bar.md`
