### ISSUE TITLE
Several Documentation links not found (404)

### ISSUE THREAD

**Issue by nicogenz** [fastify/website-metalsmith#308]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.25.0

### Node.js version

16

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

Some Documentation links are currently pointing into nowhere (404). This is probably related to the following PR where the documentation has been reworked, https://github.com/fastify/fastify/pull/3474, which has been released with version 3.25.0. 
For example the link for the "Recommendations" in the README.md is still pointing to https://github.com/fastify/fastify/blob/main/docs/Recommendations.md however it should point to https://github.com/fastify/fastify/blob/main/docs/Guides/Recommendations.md. 
The same appears on the website. If you search for "Recommendations" it navigates you to the wrong url:
![image](https://user-images.githubusercontent.com/34741282/146027632-5cd6b3de-a847-4fa7-9421-1a853a50bf93.png)

### Steps to Reproduce

* Search for Recommandations in the search field on the website
or
* Click the Recommendations link in the README.md

### Expected Behavior

It should navigate to the new docs location.

**Comment by luisorbaiceta** [comment]
This is probably related to the index of Algolia. We need to update it. Someone with access should check @mcollina @jsumners
This link is working from the toc.

**Comment by jsumners** [comment]
I don't think I have access to that.

**Comment by luisorbaiceta** [comment]
cc @lmammino

**Comment by mcollina** [comment]
I think we should update https://github.com/algolia/docsearch-configs/blob/master/configs/fastify.json. I'm going to open an issue there and see. Maybe @luisorbaiceta you can take a look as well! Thanks

**Comment by jsumners** [comment]
> I think we should update [algolia/docsearch-configs@`master`/configs/fastify.json](https://github.com/algolia/docsearch-configs/blob/master/configs/fastify.json?rgh-link-date=2021-12-14T15%3A47%3A47Z). I'm going to open an issue there and see. Maybe @luisorbaiceta you can take a look as well! Thanks

😨 our docs rely on updating a config in a completely different org managed by a completely different team?

**Comment by luisorbaiceta** [comment]
If It's ok I will temporarily hide the search bar until this is solved.

> 😨 our docs rely on updating a config in a completely different org managed by a completely different team?

I agree we need a way to update the index or config via github actions in our ci

**Comment by nicogenz** [comment]
This is not only an issue on the website. Some links on the README.md of the [Fastify repo ](https://github.com/fastify/fastify) are also pointing to the wrong direction. See https://github.com/fastify/fastify/blob/main/README.md#documentation. For example the `Hooks`, `Decorators`, `Lifecycle`....
If you want I can open a PR and fix this.

**Comment by mcollina** [comment]
> If you want I can open a PR and fix this.

Go aghead!

**Comment by nicogenz** [comment]
Opened a PR for the README.md issue: https://github.com/fastify/fastify/pull/3539

**Comment by mcollina** [comment]
I fixed it
