### ISSUE TITLE
Style the new searchbox

### ISSUE THREAD

**Issue by mcollina** [fastify/website-metalsmith#310]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

In order to fix #308 #309 I have updated our algolia setup to use v3 docsearch. As a result, the searchbox now use the default algolia styling. It would be awesome to update this.

**Comment by mcollina** [comment]
cc @luisorbaiceta

**Comment by luisorbaiceta** [comment]
Seems that [docs](https://docsearch.algolia.com/docs/styling) are a work in progress (there is nothing about custom styling) and v3 is still in alpha.

**Comment by luisorbaiceta** [comment]
I will add some styling  and hopefully classnames will remain the same in the future
