### ISSUE TITLE
Create redirect for old pages

### ISSUE THREAD

**Issue by mcollina** [fastify/website-metalsmith#312]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Description

After https://github.com/fastify/fastify/pull/3474, some of the pages are now 404s if they were external links.
It would be awesome to provide some redirects for them

(I don't know how we can do this, as this is hosted on Github Pages)

### Steps to Reproduce

https://www.fastify.io/docs/latest/Routes/ is a 404, it would be great if it redirected to https://www.fastify.io/docs/latest/Reference/Routes/

**Comment by luisorbaiceta** [comment]
I'm afraid this is not possible with `Github Pages`. I have seen many "hacks" that suggest to maintain the old site setting a `<link rel="canonical" href="{{THE_NEW_URL}}" />`. But this won't work for us because we have changes the docs structure.

In my opinion we have to assume that with a clarification and reorganization of the docs, and without a hosting provider that allows custom redirects, either we assume this as a lost case, or we search for a new hosting provider that supports redirects and rewrites.

**Comment by jaklec** [comment]
I don't know if this is of any help (sorry if I'm kicking in open doors) or if it should be posted in a separate ticket? Anyway - here's an example of a broken link I tried to reach: https://www.fastify.io/docs/latest/Reference/Guides/docs/Reference/Validation-and-Serialization

I think I found the correct docs under https://www.fastify.io/docs/latest/Reference/Validation-and-Serialization/

**Comment by luisorbaiceta** [comment]
Where did you find that link? @jaklec It's not supposed to be anywhere

**Comment by jaklec** [comment]
Hm, strange... I navigated to it through the docs menu on fastify.io about an hour ago. But now it seems to serve the correct link. Could it be my browser cache maybe? Anyway, it seems to work now :)

**Comment by luisorbaiceta** [comment]
Great. Thanks for the report!

**Comment by jaklec** [comment]
@luisorbaiceta  No sorry, I found the broken link. It's in the first paragraph on this page: https://www.fastify.io/docs/latest/Guides/Fluent-Schema/

**Comment by jsumners** [comment]
Unfortunately, without our own web server, we cannot issue proper `301`s like https://github.com/jsumners/itcouldbe9.com/blob/9b666d9f956a4eb6a7719c4f5bdea24c8949eb81/templates/nginx/jrfom.com.conf#L10-L18 . The best we can do is ask for robots to reindex.

> No sorry, I found the broken link. It's in the first paragraph on this page: [fastify.io/docs/latest/Guides/Fluent-Schema](https://www.fastify.io/docs/latest/Guides/Fluent-Schema/)

@jaklec please open an issue on the main Fastify repo for this. Submitting a PR to fix it would also be very welcome.

**Comment by luisorbaiceta** [comment]
> @jaklec please open an issue on the main Fastify repo for this. Submitting a PR to fix it would also be very welcome.

fastify/website#313

**Comment by jsumners** [comment]
> > @jaklec please open an issue on the main Fastify repo for this. Submitting a PR to fix it would also be very welcome.
> 
> #313

Oh. I thought it was broken markdown, not broken parsing of markdown.
