### ISSUE TITLE
Publish the fastify 2022 user survey as a banner

### ISSUE THREAD

**Issue by mcollina** [fastify/website-metalsmith#332]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

We need to promote our 2022 user survey in https://linuxfoundation.surveymonkey.com/r/XQX32CY.

This could be done similarly to how we added the OpenJS banner: https://github.com/fastify/website/pull/258 and https://github.com/fastify/website/pull/257.

**Comment by mcollina** [comment]
cc @luisorbaiceta would you mind to make the honors?

**Comment by luisorbaiceta** [comment]
I'll go for it tonight!

**Comment by mcollina** [comment]
thx!

**Comment by luisorbaiceta** [comment]
I'm thinking about something like: "Help us make Fastify better. Fill out our 2022 user survey"

![image](https://user-images.githubusercontent.com/44276180/153660072-b8011bc7-a066-4083-9899-11d715526cd9.png)

Thoughts?

**Comment by mcollina** [comment]
nice!

**Comment by jsumners** [comment]
Looks good. Make it so.
