### ISSUE TITLE
Docs don't let me scroll to bottom of page

### ISSUE THREAD

**Issue by cache-rules** [fastify/website-metalsmith#335]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Description

If I got to the docs page and scroll down, the browser immediately scrolls me back to the top of the page.

### Steps to Reproduce

1. Go to https://www.fastify.io/docs/latest/
2. Make sure your browser window is the full height of your screen (minus any OS taskbar). This problem will not repro if you have the window only take up _some_ of the height of your screen.
3. Attempt to scroll to the bottom of the page

This repros in Chrome and Firefox on Windows 10 and Mac OS X.

### Expected Behavior

I would expect scroll position to remain at the bottom of the page, instead I am scrolled back to the top of the page.

**Comment by luisorbaiceta** [comment]
Good catch! I'll take a look. Seems to be happening only in the root of the docs. Thanks for reporting!

**Comment by labkey-alan** [comment]
🎉 Glad I could help, keep up the good work folks.
