### ISSUE TITLE
Broken contributing/good first issues page

### ISSUE THREAD

**Issue by mcollina** [fastify/website-metalsmith#345]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Description

Open the good first issue page, it shows an error.

### Steps to Reproduce

Open the good first issue page, it shows an error.

**Comment by mcollina** [comment]
@GlenTiki could you take a look?

**Comment by xkal36** [comment]
Hi @mcollina and @GlenTiki. In discussion with @simoneb , we figured it would be best to move the code for the api to fetch gh issues to the fastify org, in a new repo and to host this on google cloud run (think you mentioned doing something in a previous issue Matteo). In any case, here is the new repo which is in the nearform org at the moment: https://github.com/nearform/gh-issues-finder. @GlenTiki this ok with you?

We are just waiting for a dev ops resource to set this up

**Comment by GlenTiki** [comment]
I'm happy for a fork to be hosted elsewhere, I've not been in this space in
a long time, so I think it makes sense for someone else to maintain that
infra :+1:

**Comment by mcollina** [comment]
I can create a google cloud run instance on Monday if needed.

**Comment by simoneb** [comment]
@ital0sant0s is working on this. once we have it working we can move it over to the fastify hosted gcp

**Comment by xkal36** [comment]
Everything is done, apart from switching the url used here: https://github.com/fastify/website/blob/f2f2bc5a8701ffcb94eb68239683ebdbf0471d2d/src/website/content/js/contribute.js#L3 to https://fastify-gh-issues-finder-5uewp47fja-uc.a.run.app/api/find-issues?org=fastify

**Comment by mcollina** [comment]
You can also use `https://goodfirstissue.fastify.io/` now

**Comment by simoneb** [comment]
@mcollina @xkal36 what's missing to do here? Can we wrap this up or are we still waiting for something else to happen?

**Comment by mcollina** [comment]
a PR to update the website to the new service.

**Comment by simoneb** [comment]
@xkal36 is this something you had started already? Can you do this since you know already what to change please?

**Comment by luisorbaiceta** [comment]
closed in #352
