### ISSUE TITLE
Scrolling the sidebar menu is difficult

### ISSUE THREAD

**Issue by jsumners** [fastify/website-metalsmith#348]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

When trying to scroll the left sidebar menu, it is not possible to reach the bottom with _also_ scrolling the overall page:

https://user-images.githubusercontent.com/321201/168860227-aee6e75f-a3e1-42e1-97a3-b6fff7d12c83.mp4

This made it really difficult to find the routing documentation that I knew was there. I kept trying to scroll the menu to see what I knew should be there, but couldn't reach it until I loaded a longer page and started scrolling that page.

**Comment by luisorbaiceta** [comment]
I'll take a look 👀
