### ISSUE TITLE
Remove the messaging that we are faster than XYZ, and focus on overhead and ease of use intead

### ISSUE THREAD

**Issue by mcollina** [fastify/website-metalsmith#36]
Currently our messaging might come out as aggressive vs the rest of the frameworks. However, we want to be good citizens of the Node.js ecosystem, and we have all used and loved the other frameworks.

How about we remove the "Yx faster than" boxes, and we adjust the rest of the messaging to that we focus on overhead and ease of use?

I've done a similar work in https://github.com/fastify/fastify/pull/358.

**Comment by delvedor** [comment]
Completely agree 👍

**Comment by jsumners** [comment]
👍
