### ISSUE TITLE
create anchors for the headings in the docs

### ISSUE THREAD

**Issue by mcollina** [fastify/website-metalsmith#37]
like github!

**Comment by lmammino** [comment]
Hey @mcollina,
I am not really sure what you mean here.

I can see both the website docs and the github docs have anchors in the titles and I can't see any mismatch between them:

- https://www.fastify.io/docs/latest/Reply/#async-await-and-promises
- https://github.com/fastify/fastify/blob/master/docs/Reply.md#async-await-and-promises

Am I missing something?

**Comment by mcollina** [comment]
I mean, it's not possible to get a link of a section from the website, while it's possible on GitHub.
If you over https://github.com/fastify/fastify/blob/master/docs/Reply.md#async-await-and-promises, the anchor symbol appears and you can click it.

Another option is to add a `#` at the end, like node core does (see https://nodejs.org/api/http2.html#http2_class_http2session).

**Comment by lmammino** [comment]
Understood now. I'll try to add this dynamically with JS after the page has been rendered so that I don't have to fiddle with the markdown rendering.

**Comment by jsumners** [comment]
This really needs to be resolved. It is very difficult to link people to specific sections (subsections) of the documentation.
