### ISSUE TITLE
I18N system

### ISSUE THREAD

**Issue by AugustinMauroy** [fastify/website-metalsmith#374]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I propose to add an I18N system. 
It could be a `dropdown or a simple `select`.
This system would work for all possible languages

### Motivation

This will allow a maximum of people to easily understand the contents of the site.

**Comment by Uzlopak** [comment]
It makes no sense to provide a i18n system if we have not translated all the content to different languages.

**Comment by luisorbaiceta** [comment]
See #92
