### ISSUE TITLE
NaN req/sec on benchmarks page

### ISSUE THREAD

**Issue by puckey** [fastify/website-metalsmith#386]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Description

Some of the benchmarks at https://www.fastify.io/benchmarks/ are reported as `NaN` req/sec.

### Steps to Reproduce

Visit https://www.fastify.io/benchmarks/

**Comment by RafaelGSS** [comment]
Looking to it

**Comment by RafaelGSS** [comment]
It wasn't fixed yet.
