### ISSUE TITLE
Divide the plugins in the ecosystem page into core and community

### ISSUE THREAD

**Issue by lmammino** [fastify/website-metalsmith#39]

**Comment by lmammino** [comment]
Also, as suggested by @mcollina in #38, we shouldn't try to parse the file ourselves in a "hacky" way, but maybe just use a rendered version of the markdown file.

**Comment by StarpTech** [comment]
It's something off-topic but this could be part of this issue, we should provide a search because I think the list will grow fast. We could then mark community and team plugins by stickers or medals 🥇Just an idea.

- Lightweight fuzzy-search http://fusejs.io/
- https://github.com/choojs/choo

**Comment by mcollina** [comment]
Fixed in #121
