### ISSUE TITLE
Broken link on https://www.fastify.io/docs/latest/Getting-Started/

### ISSUE THREAD

**Issue by akaila** [fastify/website-metalsmith#40]
Search and click on the word "ecosystem" and it throws 404

**Comment by trivikr** [comment]
Looks like the link is not updated https://www.fastify.io/docs/latest/Ecosystem
The "Ecosystem" link in Navigation redirects to https://www.fastify.io/ecosystem/

**Comment by mcollina** [comment]
Good spot! We are (as always) very busy.. would you like to send a PR?
