### ISSUE TITLE
Why not run on fastify when you are promoting it?

### ISSUE THREAD

**Issue by binarykitchen** [fastify/website-metalsmith#410]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I was surprised that fastify isn't listed as a dependency in package.json.

Isn't this your official website where you are promoting fastify? The more a reason to run on it. Or else it feels like a contradiction.

### Motivation

Running your official site on fastify would help you to spot more bugs and could make another good showcase how fastify can help to build websites like these.

**Comment by jsumners** [comment]
The website is static HTML hosted via GitHub. There's no need to write an API server with Fastify to host any portion of the site.

**Comment by binarykitchen** [comment]
Understand. 

Yet, you still could serve some server-sided rendered React contents with a simple API call at least? Or implement a proper contact page for form submission? In due time, you might need API paths.

It just looks odd. There are official fastify plugins for serving static HTML.

**Comment by mcollina** [comment]
Sure but why spending money to run servers when hosting a static website can be done mostly for free? Fastify is not a company and foundation money is precious.

**Comment by Eomm** [comment]
IMHO https://dev.to/dvddpl/the-screw-and-the-hammer-love-the-problems-not-your-solutions-2i0a

> Ferrari does not use Ferraris as golf cars

cit myself

**Comment by binarykitchen** [comment]
Appreciate your honesty. While we are at it, allow me to be honest as well:

If you sell fastify for high-traffic websites only outside the "golf course", then please mention it. For low/medium traffic, Express.js is probably good enough. Is this mentioned?

PS: when all you have is a hammer, everything looks like a nail ...

**Comment by mcollina** [comment]
Let me be clear: the OpenJS Foundation is not selling Fastify. There is no Fastify plans to buy or anything else. Fastify is not a company - it's a community of people maintaining a framework for Node.js. You can decide to be part of that or not.

Express has been in maintenance mode for many years now, there are plenty of reasons to not use express. As far as I know, it is maintained by a single person. If express works for you, keep going.

On the current matter, serving static files is not a good use of Node.js to begin with. In fact, even the Node.js website does not use Node.js to serve static files. It uses NGINX.

**Comment by kibertoad** [comment]
>If you sell fastify for high-traffic websites only outside the "golf course", then please mention it. For low/medium traffic, Express.js is probably good enough. Is this mentioned?

Express is not only slower, it is also offers inferior developer experience: no lifecycle hooks, inferior promise support, poor TypeScript support etc.

There are no technical reasons to create anything in Express.js in 2023. With all due respect to the historical importance of Express, It has since been leapfrogged by the majority of active framework on the market right now, and learning something better is not that hard.

**Comment by Uzlopak** [comment]
I agree, with you @binarykitchen: If you have a hammer, everything looks like a nail. But we dont have only a hammer. And using a framework, which is optimized for use as a api server, to serve static files, is obviously the wrong tool For this we have nginx. 

Why should we recommend expressjs as framework for api servers, if it is obviously the inferior product? Also using expressjs for serving static files is just plain wrong.

**Comment by binarykitchen** [comment]
Thank you, everyone. 

Apologies for being a bit off the rails. Had a few good email exchanges with Matteo.

Submitted a [PR](https://github.com/fastify/website/pull/411) for a new FAQ section. It says all :)
