### ISSUE TITLE
where can I submit my plugin?

### ISSUE THREAD

**Issue by PavloPoliakov** [fastify/website-metalsmith#46]
Hi,

I just released another fastify plugin [fastify-blipp](https://github.com/PavelPolyakov/fastify-blipp).

I know my plugin is pretty dumb, but still think it can be useful :) Wanted to submit it to be present in the plugins list here:
https://www.fastify.io/ecosystem/

However I see that `ecosystem.yml` reference is broken:
https://github.com/fastify/fastify/docs/_data/ecosystem.yml

And I was not able to find the source of the plugins list in the website repository.

What is the current way to submit plugin PR?

Regards,

**Comment by delvedor** [comment]
Hi!
Just open a pr in the main repo, following you can see other similar prs :)
https://github.com/fastify/fastify/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3Aplugin

**Comment by PavloPoliakov** [comment]
@delvedor thanks!
