### ISSUE TITLE
Request to use favicon.ico in a plugin

### ISSUE THREAD

**Issue by smartiniOnGitHub** [fastify/website-metalsmith#48]
Hi all,
in a plugin I'm writing [fastify-favicon](https://github.com/smartiniOnGitHub/fastify-favicon) I'd like (if possible) to use standard fastify favicon.
Or maybe I could load it from Fastify directly but currently it's not in that repository.
What do you think ?

Thanks a lot,
Sandro

**Comment by mcollina** [comment]
All of the originals are in https://github.com/fastify/graphics. You can bundle them, I would not depend on a internet accessible resource. Please keep the attribution to the logo.

**Comment by smartiniOnGitHub** [comment]
@mcollina Yes I think that including it in the plugin is the best option (unless it will be bundled in fastify). 
Sorry but I found the favicon not in fastify/graphics repo but in fastify/website repo, [here](https://github.com/fastify/website/blob/master/src/website/content/favicon.ico).
License of the plugin is Apache so it's compatible with MIT license used here, and I'll put attributions in the NOTICE file. Thanks :-) .
