### ISSUE TITLE
https://github.com/fastify/fastify/docs/_data/ecosystem.yml returns 404

### ISSUE THREAD

**Issue by charlesread** [fastify/website-metalsmith#49]
The very bottom of https://www.fastify.io/ecosystem/ links to https://github.com/fastify/fastify/docs/_data/ecosystem.yml, but it is not found.

**Comment by mcollina** [comment]
ouch! Thanks! Would you like to contribute a fix?

**Comment by charlesread** [comment]
I'd be more than happy to do so, but I don't know what is _meant_ to be on that page.  Initially I thought that `ecosystem.yml` might just be in a different location than the referenced location, but I couldn't find the file at all in the repo, so I don't know what that page actually needs to display.

**Comment by jsumners** [comment]
I think this is very related to https://github.com/fastify/fastify/issues/801

**Comment by charlesread** [comment]
ping @mcollina

**Comment by mcollina** [comment]
It needs to point to https://github.com/fastify/fastify/blob/master/docs/Ecosystem.md.
