### ISSUE TITLE
Review copywriting

### ISSUE THREAD

**Issue by lmammino** [fastify/website-metalsmith#5]
Here is a list of the files that might require some attention:

- [metadata.json](https://github.com/fastify/website/blob/master/src/website/metadata.json) - Contains some generic metadata used all over the website (it can also be used to specify a google analytics track id, in case you have one you want to use to track website visits.
- [acknowledgements.yml](https://github.com/fastify/website/blob/master/src/website/data/acknowledgements.yml) - structured data used to build the acknowledgement list on the home page
- [benchmarks.yml](https://github.com/fastify/website/blob/master/src/website/data/benchmarks.yml) - Structured data used to build the benchmark page
- [ecosystem.yml](https://github.com/fastify/website/blob/master/src/website/data/ecosystem.yml) - Structured data for the list of plugins, used both on the home page and in the ecosystem page
- [team.yml](https://github.com/fastify/website/blob/master/src/website/data/team.yml) - Structured data for the team section on the home
- [error.md](https://github.com/fastify/website/blob/master/src/website/content/error.md) - Content for the 404 page
- [home.html](https://github.com/fastify/website/blob/master/src/website/layouts/home.html) - Layout for the home page ([nunjucks](https://mozilla.github.io/nunjucks/) syntax)
- [ecosystem.html](https://github.com/fastify/website/blob/master/src/website/layouts/ecosystem.html) - Layout for the ecosystem page ([nunjucks](https://mozilla.github.io/nunjucks/) syntax)
- [docs_page.html](https://github.com/fastify/website/blob/master/src/website/layouts/docs_page.html) - Layout for the documentation page ([nunjucks](https://mozilla.github.io/nunjucks/) syntax)
- [benchmarks.html](https://github.com/fastify/website/blob/master/src/website/layouts/benchmarks.html) - Layout for the benchmark page ([nunjucks](https://mozilla.github.io/nunjucks/) syntax)

In case you want to see the outcome of the changes locally, before submitting the PR you should find all the necessary instructions to do so in the [README](https://github.com/fastify/website/blob/master/README.md#build).

**Comment by lmammino** [comment]
@mcollina @delvedor I guess at this stage we can close this one, right?

**Comment by delvedor** [comment]
I think so :D
