### ISSUE TITLE
Broken link in Documentation for Server-Methods

### ISSUE THREAD

**Issue by lmammino** [fastify/website-metalsmith#50]
In the [Server-Methods doc page](https://www.fastify.io/docs/latest/Server-Methods/) the link to `Fastify factory function` is broken.

This might be only one of many broken links, as it is probably due to the way the markdown file is processed and the links are altered to match the website URL.

Refs:
 - https://github.com/fastify/fastify/pull/819
 - https://github.com/fastify/fastify/issues/801

**Comment by mcollina** [comment]
I think this coule be closed now
