### ISSUE TITLE
LTS missing in Doc section

### ISSUE THREAD

**Issue by allevo** [fastify/website-metalsmith#55]
[https://www.fastify.io/docs/latest/](https://www.fastify.io/docs/latest/) doesn't list [LTS docs](https://github.com/fastify/fastify/blob/master/docs/LTS.md)

**Comment by lmammino** [comment]
The list of pages available in the docs is taken from the main [README](https://github.com/fastify/fastify#documentation).

We should add LTS there to have it working.

If this is not ideal (e.g. we don't want to link the LTS there), then we need to find another process to maintain a ToC for the website.

**Comment by delvedor** [comment]
I think we can directly read what is inside the `docs` folder and add an `ignore` field here if in the future we want to "hide" some page.

**Comment by mcollina** [comment]
That list in the readme also control the order. We need some sort of ToC anyway.

**Comment by lmammino** [comment]
Any reason why LTS cannot be part of the main ToC in fastify README.md?

**Comment by mcollina** [comment]
It needs a PR.
