### ISSUE TITLE
Configure CI

### ISSUE THREAD

**Issue by lmammino** [fastify/website-metalsmith#6]
- [x] 1. Enable trigger on website repository commits
- [x] 2. Enable trigger on fastify repository commits
- [x] 3. Prepare fastify AWS S3 bucket for deploy
- [x] 4. Configure CI environment variables (AWS credentials + Bucket Name)
- [x] 5. Map custom domain to S3 bucket website (Depends on #7)

**Comment by lmammino** [comment]
@mcollina, I can't currently access the settings in this repo (probably because I am not an admin in the specific repo), so I won't be able to configure GitHub integrations with Circle CI.

**Comment by mcollina** [comment]
you should be an admin right now.

**Comment by lmammino** [comment]
Thanks @mcollina

**Comment by lmammino** [comment]
I requested access to use Cirlce CI with the repos in this organisation

**Comment by delvedor** [comment]
I gave the authorization :)

**Comment by lmammino** [comment]
Trigger on website changes is enabled (for now still publishing on my s3 bucket).
I will try to figure out what's the best way to trigger the website build also when there's a change on master in the main fastify repo.

**Comment by lmammino** [comment]
I suppose this one is done as well. I'll leave the honor to close it to you guys 😆
