### ISSUE TITLE
Factory documentation is missing

### ISSUE THREAD

**Issue by delvedor** [fastify/website-metalsmith#61]
As titled.

Now I have no time to fix, if someone wants to fix it go ahead! :)
https://github.com/fastify/fastify/blob/master/docs/Factory.md

**Comment by lmammino** [comment]
In order to fix this issue, we need to add a link to this section in the main README in the main Fastify repo: https://github.com/fastify/fastify/blob/master/README.md#documentation. I'll submit a PR shortly
