### ISSUE TITLE
Link to fastify-cli in the homepage

### ISSUE THREAD

**Issue by mcollina** [fastify/website-metalsmith#67]
See https://github.com/fastify/fastify/issues/1011

**Comment by luisorbaiceta** [comment]
@mcollina do you still want this to happen? In my opinion it will be helpful for new developers using fastify

**Comment by marcodev86** [comment]
Something like that?

![Fastify-cli](https://user-images.githubusercontent.com/3684662/152888757-d2619c9f-ff85-4381-ae08-0791a4ed507d.png)

**Comment by mcollina** [comment]
That'd be great, thx!

**Comment by marcodev86** [comment]
I'm doing the pull request this evening.
