### ISSUE TITLE
Register/Reserve Domain name

### ISSUE THREAD

**Issue by lmammino** [fastify/website-metalsmith#7]
We should have a proper domain name for exposing the website to the world. I see that `fastify.com` is taken. In case none of you is the owner of that domain we can maybe try to get `fastify.js.org` through [dns.js.org](https://dns.js.org/).

**Comment by delvedor** [comment]
What about `fastify.io`?

**Comment by lmammino** [comment]
I really like it as well :) We should make up our mind soon and register the domain we choose quickly

**Comment by mcollina** [comment]
We have `fastify.io`.

**Comment by lmammino** [comment]
💣
