### ISSUE TITLE
Create a new page on fastify users

### ISSUE THREAD

**Issue by mcollina** [fastify/website-metalsmith#73]
As titled!

**Comment by lmammino** [comment]
Following on from our conversation yesterday, let's get this one restarted.

## Idea

We want to showcase a list of brands/companies adopting fastify. We can have a brief list with the top N in the home page of the website and in the main README of the repository and potentially an entire page listing all of them.

For every company/brand we will display a logo (possibly vector and grayscale) and (optionally) have a link to their home page.


## Plan

 1. First of all I would collect at least 4 names/logos we can use to bootstrap the section and let's build the pages.
 2. We have to define what is the process to add more brands and have it written both in the website and the project main README. Aspirationally this process should be fulfilled only throught a GitHub PR.
 3. We can automate the PR changes in the website build to have everything automated: once the PR is approved and merged, as part of our build process, the logo will automatically appear on the website.

@mcollina  @jsumners  @allevo  @delvedor @evanshortiss et al., what do you think about this approach? Did you have a different idea?

Looking forward to hearing from you.

**Comment by mcollina** [comment]
I'm +1.

**Comment by jsumners** [comment]
I think this proposal is acceptable. 

Knock would like to be part of the list.

@joeshehata, Karan says you have the materials that would be needed to participate. Looping you in here so it's on your radar.

**Comment by delvedor** [comment]
👍

**Comment by lmammino** [comment]
@jsumners great stuff, I am trying to get approval to be able to add the company i work for.
Do we have at least 4 brands to get this started? @mcollina @delvedor @allevo are "your" companies interested in having some space there?

**Comment by mcollina** [comment]
I would need confirmation, but I don't see any obstacles in adding NearForm there (it's already in the Readme).

cc @thearegee are you folks interested?

**Comment by robinglen** [comment]
@mcollina I would be interested in this for sure. I'm also currently writing a medium post about our use of fastify, so maybe we could line this up.

Would need speak to our comms team if you want anything more than a logo but I see no issue. Let know what you would need from me.

**Comment by mcollina** [comment]
I think a logo would be enough. What do you think @lmammino?

**Comment by lmammino** [comment]
I'd say logo & link to the main website. At this stage, we are not interested in quotes or use case stories/posts.

**Comment by robinglen** [comment]
So although we are rolling it out to multiple brands, we are currently only in production for one of them. As you want to link to the site I think it makes sense to only show that one.

Let me know how you want me to submit logo url and I'm happy for us to be on there.

**Comment by lmammino** [comment]
@thearegee, ideally it would be an SVG file. I am [currently experimenting with the design](#77). As soon as I am sure what's the best way to display the logos I'll write down the specs for the file and give you all the details.

**Comment by allevo** [comment]
@lmammino Yeah, I'll send the request to my boss but I don't see any drawbacks
