### ISSUE TITLE
Language selection / i18n

### ISSUE THREAD

**Issue by cemremengu** [fastify/website-metalsmith#92]
We should a dropdown for i18n so that users can view the chinese docs and any other languages

**Comment by lmammino** [comment]
Good one.
Are we assuming other translations will be living in another website/url or do we want to have a more sophisticated build process here to be able to handle multilanguage internally?

**Comment by cemremengu** [comment]
I think its better if translations come from somewhere else in the specified format and we just display them. I mean something like this one:

https://github.com/eggjs/egg/tree/master/docs/source

**Comment by cemremengu** [comment]
For reference docs for chinese live [here](https://github.com/fastify/docs-chinese)

**Comment by lmammino** [comment]
Thanks!
For now we have onlu chinese translations, right?

I am trying to figure out if we can avoid dropdowns (which are not the most usable thing ever)

**Comment by cemremengu** [comment]
For now yes, so we can just do `English | Chinese` selection I think

**Comment by wallasfmorais** [comment]
I could do it for Portuguese (Brazilian Portuguese), I'm wondering if this is desired.
Are there few Fastify tutorials in the ptbr language (in any language to be fair compared to so many libraries)? I am planning to start doing some "evangelism" about it on ptbr by creating various types of content.
Anyway, let me know if any of these "works" would be appreciated.

**Comment by mcollina** [comment]
I'm not sure we can commit to keep the docs up-to-date in all languages. I'm happy to have a repo similar to https://github.com/fastify/docs-chinese for Portuguese if you'd like to work on that!

**Comment by lmammino** [comment]
I am happy to find ways to add links to the website, but I would agree with @mcollina. It's very very hard to keep documentation in sync in multiple languages. I'd prefer to be clear and say that there's one official documentation in English and that the other ones are there for convenience but might not necessarily be always up to date.

**Comment by wallasfmorais** [comment]
> I'm not sure we can commit to keep the docs up-to-date in all languages. I'm happy to have a repo similar to https://github.com/fastify/docs-chinese for Portuguese if you'd like to work on that!

I sure would. Once the repository is created, I can start.

**Comment by mcollina** [comment]
@wallasfmorais repo created, and I've got you invited there!

**Comment by luisorbaiceta** [comment]
closing this for now, since there is not foresight of maintaining multiple languages
