### ISSUE TITLE
Document returning a stream from a route

### ISSUE THREAD

**Issue by seangenabe** [fastify/website-metalsmith#96]
re: https://github.com/fastify/fastify/issues/23

**Comment by cemremengu** [comment]
Would you like to send a PR? :) (to the main repo)

**Comment by delvedor** [comment]
The pr should be done in the main repo :)

**Comment by cemremengu** [comment]
@seangenabe it is actually documented here https://www.fastify.io/docs/latest/Reply/#streams

Does that help?

**Comment by cemremengu** [comment]
@delvedor maybe we can use the new "move issue" feature? :D

**Comment by delvedor** [comment]
> @seangenabe it is actually documented here fastify.io/docs/latest/Reply/#streams

You are right!

> @delvedor maybe we can use the new "move issue" feature? :D

We could, but in this case we can skip it since the feature is already documented :)
